input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  mutate {
    add_field => { "scenario" => "03-healthcare-data-broker" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "medical-telemetry-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
